version: '3'
services:
notebook:
  build: .
  ports:
    - "8888:8888"
  volumes:
    - ./workspace:/workspace
  environment:
    - JUPYTER_ENABLE_LAB=yes
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [GPU]